spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/1809
    username: root
    password: 2001
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/1809a
mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  ##*typeAliasesPackage: com.jk.bean

  redis:
    #redis数据库地址
     host: localhost
     port: 6379
     password:
     timeout: 1000
     #redis数据库索引，默认0
     database: 1




